#!/usr/bin/env bash

# You could symlink this to path.

set -eo pipefail

script_dir="$(dirname "$(readlink -f "${BASH_SOURCE[@]}")")"

[[ -z $CHATGPT_CONTEXT ]] && CHATGPT_CONTEXT="$(pwd | tr -d '/')"
CHATGPT_CONTEXT="$CHATGPT_CONTEXT" OPENAI_API_KEY="${OPENAI_API_KEY}" python3 "$script_dir/chatgpt.py" "$@"
