[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
  "requests",
  "openai==1.2.3",
  "rxpy",
  "appdirs",
]
name = "chatgpt-cli"
version = "1.1.0"
