[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
dependencies = [
  "requests",
  "openai==1.12.0",
  "rxpy",
  "appdirs",
  "anthropic"
]
name = "chatgpt-cli"
version = "1.1.0"
